### ISSUE TITLE
Very limited vertical space for content on many laptops

### ISSUE THREAD

**Issue by eweitz** [NCBI-Hackathons/ncbi-hackathons.github.io#3]
Hello!  Kudos on [the tweet from NCBI](https://twitter.com/NCBI/status/849705727824453632).  While browsing around the site in my 13" laptop, I noticed there's very little vertical space available for content.

http://viewportsizes.com/mine/ says I'm on a 1280 × 682 viewport.  My guess is that's roughly the default size for maximized windows on 13" laptops like mine, which are pretty common.

I fixed this in Chrome DevTools for my particular case like so:
* Move `footer` outside current containing element `<div class="container-fluid main-container">`
* Remove class `navbar-fixed-bottom` from that `footer` element

I'm not otherwise familiar with this site's underlying code (hence no PR at the moment), but hopefully that helps.

In any case, below is a screenshot of what I see on https://ncbi-hackathons.github.io/Expression.html:
![squished_content_in_13-inch_mbp](https://cloud.githubusercontent.com/assets/1334561/24725441/f6d9570e-1a1c-11e7-98d8-f95329f6fe8a.png)

**Comment by amanjeev** [comment]
@DCGenomics Please feel free to assign it to anyone who can take care of this.

**Comment by brianzelip** [comment]
Thanks @eweitz. Fixed via [this commit](https://github.com/NCBI-Hackathons/ncbi-hackathons.github.io/commit/029fa8c35f574c05df9f9c654922253815ad62c9).
