### ISSUE TITLE
manuscript

### ISSUE THREAD

**Issue by brianzelip** [NCBI-Hackathons/ncbi-hackathons.github.io#4]
https://github.com/NCBI-Hackathons/ncbi-hackathons.github.io

**Comment by brianzelip** [comment]
what happens when there's another comment?

**Comment by amanjeev** [comment]
You get a response acknowledging your comment. :-)

**Comment by brianzelip** [comment]
:)

hi @amanjeev 

(fyi - I'm testing out issue labels and issue bodies as metadata to programmatically flesh out bits for the list of products shipped from NCBI hackathons. See https://gist.github.com/brianzelip/34c7ae7fae90122c45d624fb20aa670b)

**Comment by brianzelip** [comment]
rm "manuscript" label for the general "metadata"
